require('dotenv').config();
const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const morgan = require('morgan');
const rateLimit = require('express-rate-limit');
const config = require('./utils/config');
const { errorHandler } = require('./middleware/errorHandler');
const authRoutes = require('./routes/auth');
const servicesRoutes = require('./routes/services');
const ordersRoutes = require('./routes/orders');
const paymentsRoutes = require('./routes/payments');
const supportRoutes = require('./routes/support');
const notificationsRoutes = require('./routes/notifications');
const adminRoutes = require('./routes/admin');
const app = express();
app.use(helmet());
app.use(cors({ origin: config.NODE_ENV === 'production' ? config.CORS_ORIGIN : '*', credentials: true }));
const limiter = rateLimit({ windowMs: config.RATE_LIMIT_WINDOW_MS, max: config.RATE_LIMIT_MAX, standardHeaders: true, legacyHeaders: false, message: { error: 'Too many requests.' } });
app.use('/api/', limiter);
const authLimiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 20, message: { error: 'Too many auth attempts.' } });
app.use('/api/auth/login', authLimiter);
app.use('/api/auth/register', authLimiter);
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: true, limit: '1mb' }));
if (config.NODE_ENV !== 'test') app.use(morgan('combined'));
app.get('/api/health', (_req, res) => res.json({ status: 'ok', timestamp: new Date().toISOString(), environment: config.NODE_ENV }));
app.use('/api/auth', authRoutes);
app.use('/api/services', servicesRoutes);
app.use('/api/orders', ordersRoutes);
app.use('/api/payments', paymentsRoutes);
app.use('/api/support', supportRoutes);
app.use('/api/notifications', notificationsRoutes);
app.use('/api/admin', adminRoutes);
app.use((_req, res) => res.status(404).json({ error: 'Endpoint not found.' }));
app.use(errorHandler);
if (require.main === module) { app.listen(config.PORT, config.HOST, () => { console.log(`NovaPay API running on http://${config.HOST}:${config.PORT}`); console.log(`Environment: ${config.NODE_ENV}`); }); }
module.exports = app;